foro/config/routes.rb
Rails.application.routes.draw do
  resources :comentarios

  resources :temas

  resources :tags

  resources :usuarios

end

foro/app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :tema
end

foro/app/models/tag.rb
class Tag < ActiveRecord::Base
end

foro/app/models/tema.rb
class Tema < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :tag
end

foro/app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

foro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

foro/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:usuario_id, :tema_id, :comentario, :fecha, :like)
    end
end

foro/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:nombre)
    end
end

foro/app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_action :set_tema, only: [:show, :edit, :update, :destroy]

  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
  end

  # GET /temas/new
  def new
    @tema = Tema.new
  end

  # GET /temas/1/edit
  def edit
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(tema_params)

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema was successfully created.' }
        format.json { render :show, status: :created, location: @tema }
      else
        format.html { render :new }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temas/1
  # PATCH/PUT /temas/1.json
  def update
    respond_to do |format|
      if @tema.update(tema_params)
        format.html { redirect_to @tema, notice: 'Tema was successfully updated.' }
        format.json { render :show, status: :ok, location: @tema }
      else
        format.html { render :edit }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema.destroy
    respond_to do |format|
      format.html { redirect_to temas_url, notice: 'Tema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tema
      @tema = Tema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tema_params
      params.require(:tema).permit(:usuario_id, :titulo, :resena, :tag_id, :like)
    end
end

foro/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :password, :correo, :firma, :username, :numeromiembro)
    end
end

foro/app/helpers/application_helper.rb
module ApplicationHelper
end

foro/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

foro/app/helpers/tags_helper.rb
module TagsHelper
end

foro/app/helpers/temas_helper.rb
module TemasHelper
end

foro/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

foro/app/views/comentario/_form.html.erb
<%= form_for @comentario, :html => { :class => "form-horizontal comentario" } do |f| %>

    <% if @comentario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @comentario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :usuario_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :usuario_id, :class => 'form-control' %>
    </div>
    <%= error_span(@comentario[:usuario_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :tema_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tema_id, :class => 'form-control' %>
    </div>
    <%= error_span(@comentario[:tema_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :comentario, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comentario, :class => 'form-control' %>
    </div>
    <%= error_span(@comentario[:comentario]) %>
  </div>
  <div class="control-group">
    <%= f.label :fecha, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fecha, :class => 'form-control' %>
    </div>
    <%= error_span(@comentario[:fecha]) %>
  </div>
  <div class="control-group">
    <%= f.label :like, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :like, :class => 'form-control' %>
    </div>
    <%= error_span(@comentario[:like]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            comentarios_path, :class => 'btn btn-default' %>

<% end %>

foro/app/views/comentario/edit.html.erb
<%- model_class = Comentario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

foro/app/views/comentario/index.html.erb
<%- model_class = Comentario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:usuario_id) %></th>
      <th><%= model_class.human_attribute_name(:tema_id) %></th>
      <th><%= model_class.human_attribute_name(:comentario) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:like) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= link_to comentario.id, comentario_path(comentario) %></td>
        <td><%= comentario.usuario_id %></td>
        <td><%= comentario.tema_id %></td>
        <td><%= comentario.comentario %></td>
        <td><%= comentario.fecha %></td>
        <td><%= comentario.like %></td>
        <td><%=l comentario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comentario_path(comentario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comentario_path(comentario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comentario_path,
            :class => 'btn btn-primary' %>

foro/app/views/comentario/new.html.erb
<%- model_class = Comentario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

foro/app/views/comentario/show.html.erb
<%- model_class = Comentario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:usuario_id) %>:</strong></dt>
  <dd><%= @comentario.usuario_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tema_id) %>:</strong></dt>
  <dd><%= @comentario.tema_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comentario) %>:</strong></dt>
  <dd><%= @comentario.comentario %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @comentario.fecha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:like) %>:</strong></dt>
  <dd><%= @comentario.like %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              comentarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comentario_path(@comentario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comentario_path(@comentario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

foro/app/views/comentarios/edit.html.erb
<%- model_class = Comentario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

foro/app/views/comentarios/index.html.erb
<%- model_class = Comentario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:usuario_id) %></th>
      <th><%= model_class.human_attribute_name(:tema_id) %></th>
      <th><%= model_class.human_attribute_name(:comentario) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:like) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= link_to comentario.id, comentario_path(comentario) %></td>
        <td><%= comentario.usuario_id %></td>
        <td><%= comentario.tema_id %></td>
        <td><%= comentario.comentario %></td>
        <td><%= comentario.fecha %></td>
        <td><%= comentario.like %></td>
        <td><%=l comentario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comentario_path(comentario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comentario_path(comentario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comentario_path,
            :class => 'btn btn-primary' %>

foro/app/views/comentarios/new.html.erb
<%- model_class = Comentario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

foro/app/views/tag/index.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.id, tag_path(tag) %></td>
        <td><%= tag.nombre %></td>
        <td><%=l tag.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tag_path(tag), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tag_path(tag),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tag_path,
            :class => 'btn btn-primary' %>

foro/app/views/tags/index.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.id, tag_path(tag) %></td>
        <td><%= tag.nombre %></td>
        <td><%=l tag.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tag_path(tag), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tag_path(tag),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tag_path,
            :class => 'btn btn-primary' %>

foro/app/views/tema/index.html.erb
<%- model_class = Tema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:usuario_id) %></th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:resena) %></th>
      <th><%= model_class.human_attribute_name(:tag_id) %></th>
      <th><%= model_class.human_attribute_name(:like) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @temas.each do |tema| %>
      <tr>
        <td><%= link_to tema.id, tema_path(tema) %></td>
        <td><%= tema.usuario_id %></td>
        <td><%= tema.titulo %></td>
        <td><%= tema.resena %></td>
        <td><%= tema.tag_id %></td>
        <td><%= tema.like %></td>
        <td><%=l tema.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tema_path(tema), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tema_path(tema),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tema_path,
            :class => 'btn btn-primary' %>

foro/app/views/temas/index.html.erb
<%- model_class = Tema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:usuario_id) %></th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:resena) %></th>
      <th><%= model_class.human_attribute_name(:tag_id) %></th>
      <th><%= model_class.human_attribute_name(:like) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @temas.each do |tema| %>
      <tr>
        <td><%= link_to tema.id, tema_path(tema) %></td>
        <td><%= tema.usuario_id %></td>
        <td><%= tema.titulo %></td>
        <td><%= tema.resena %></td>
        <td><%= tema.tag_id %></td>
        <td><%= tema.like %></td>
        <td><%=l tema.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tema_path(tema), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tema_path(tema),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tema_path,
            :class => 'btn btn-primary' %>

foro/app/views/usuario/index.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:apellido) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:correo) %></th>
      <th><%= model_class.human_attribute_name(:firma) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:numeromiembro) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.password %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.firma %></td>
        <td><%= usuario.username %></td>
        <td><%= usuario.numeromiembro %></td>
        <td><%=l usuario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      usuario_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_usuario_path,
            :class => 'btn btn-primary' %>

foro/app/views/usuarios/index.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:apellido) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:correo) %></th>
      <th><%= model_class.human_attribute_name(:firma) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:numeromiembro) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.password %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.firma %></td>
        <td><%= usuario.username %></td>
        <td><%= usuario.numeromiembro %></td>
        <td><%=l usuario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      usuario_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_usuario_path,
            :class => 'btn btn-primary' %>